project:
  type: website
  output-dir: docs
website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - href: "https://github.com/PushpakSunilRane"
        icon: github
      - href: "https://www.linkedin.com"
        icon: linkedin
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

