project:
  type: website
  output-dir: docs
website:
  title: "Portfolio"
  search: false
  navbar:
    right: 
      - href: "https://github.com/PushpakSunilRane"
        icon: github
      - href: "https://www.linkedin.com"
        icon: linkedin
format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

